Add howto build description
savushkin-r-d/ptusa_main pull request #220
Opened 2021-03-12 13:20 UTC by idzm

Fixes #216.

2021-03-12 13:28 UTC, dimabeel requested changes

2021-03-12 13:28 UTC, dimabeel commented on readme.md
> +You should open (in Visual Studio) directory **PAC_control_projects\main_control_prg\eclipse\projects\PLCnext-linux-PLCnextEngineer**. Thus you get a CMake based project.
```suggestion
You should open (in Visual Studio) directory **PAC_control_projects\main_control_prg\eclipse\projects\PLCnext-linux-PLCnextEngineer**. This you get a CMake based project.
```

2021-03-15 07:16 UTC, dimabeel submitted a review, later dismissed

2021-03-26 06:11 UTC, dimabeel requested changes

2021-03-26 06:11 UTC, dimabeel commented on readme.md
> +where `<build_name>` - used build configuration name.
Need to add possible names of build

2021-03-26 09:06 UTC, dimabeel approved these changes

2021-03-26 12:57 UTC, rartem approved these changes

2021-03-26 12:57 UTC, merged