Changes to be able to use ptusa_tests
savushkin-r-d/ptusa_main pull request #258
Opened 2021-05-12 07:33 UTC by vals-dev

2021-05-12 13:51 UTC, idzm requested changes
Small changes in code formatting are required.

2021-05-12 13:51 UTC, idzm commented on PAC/common/tcp_cmctr.cpp
> +       is_init = true;
```suggestion
    if ( !is_init )
       {
       is_init = true;
```

2021-05-12 14:00 UTC, vals-dev commented on PAC/common/tcp_cmctr.cpp
> +       is_init = true;
Commited

2021-05-13 05:27 UTC, idzm approved these changes

2021-05-14 05:59 UTC, rartem approved these changes

2021-05-14 06:37 UTC, merged