Add Signal column to control devices
savushkin-r-d/ptusa_main pull request #272
Opened 2021-06-15 13:50 UTC by idzm

Fixes #207.

2021-06-16 05:18 UTC, dimabeel requested changes

2021-06-16 05:18 UTC, dimabeel commented on PAC/common/PAC_dev.cpp
> +    blink( (u_int)DO_CONSTANTS::INDEX_GREEN, yellow,
```suggestion
    blink( (u_int)DO_CONSTANTS::INDEX_GREEN, green,

```

2021-06-16 05:18 UTC, dimabeel commented on PAC/common/PAC_dev.cpp
> +    set_DO( (u_int)DO_CONSTANTS::INDEX_SIREN, 0 );
Почему бы не использовать turn_off_siren()?

2021-07-19 08:46 UTC, dimabeel approved these changes

2021-07-19 11:23 UTC, rartem approved these changes

2021-07-19 11:39 UTC, rartem approved these changes

2021-07-19 11:50 UTC, merged