Add motor additional properties
savushkin-r-d/ptusa_main pull request #284
Opened 2021-07-20 09:02 UTC by idzm

Fixes #278.

2021-07-20 09:06 UTC, dimabeel requested changes

2021-07-20 09:06 UTC, dimabeel commented on PAC/common/PAC_dev.cpp
> +    float d = get_par( P_SCHAFT_DIAMETER, 0 );
```suggestion
    float d = get_par( P_SHAFT_DIAMETER, 0 );

```

2021-07-20 09:06 UTC, dimabeel commented on PAC/common/PAC_dev.h
> +    set_par_name( P_SCHAFT_DIAMETER, 0, "P_SCHAFT_DIAMETER" );
```suggestion
    set_par_name( P_SHAFT_DIAMETER, 0, "P_SHAFT_DIAMETER" );

```

2021-07-20 09:06 UTC, dimabeel commented on PAC/common/PAC_dev.h
> +        P_SCHAFT_DIAMETER,  ///< Диаметр вала (м).
```suggestion
        P_SHAFT_DIAMETER,  ///< Диаметр вала (м).

```

2021-07-21 07:13 UTC, dimabeel approved these changes

2021-07-23 05:49 UTC, dimabeel submitted a review, later dismissed

2021-07-23 12:38 UTC, rartem submitted a review, later dismissed

2021-07-27 09:07 UTC, AlexandraNovik reviewed
Я запускала программу с новым функционалом, функция get_linear_speed() работает, есть все дополнительные теги мотора P_SHAFT_DIAMETER, P_TRANSFER_RATIO. Но насколько я понимаю, нельзя при отладке для тестирования установить параметры мотора, которые получаются от частотника (обороты в минуту, частоту и расширенное состояние).

2021-07-27 12:02 UTC, rartem approved these changes

2021-07-27 12:02 UTC, merged