Optimize print I/O modules configuration
savushkin-r-d/ptusa_main pull request #355
Opened 2022-01-27 07:53 UTC by idzm

2022-02-07 13:20 UTC, dimabeel requested changes

2022-02-07 13:20 UTC, dimabeel commented on PAC/common/bus_coupler_io.cpp
> +        DI_cnt, DI_cnt / 8, DO_cnt, DO_cnt / 8, AI_cnt, AI_size, AO_cnt, AO_size );
Magic numbers

2022-02-07 13:20 UTC, dimabeel commented on PAC/common/bus_coupler_io.cpp
> +        DI_cnt, DI_cnt / 8, DO_cnt, DO_cnt / 8, AI_cnt, AI_size, AO_cnt, AO_size );
Magic numbers

2022-02-08 05:08 UTC, dimabeel approved these changes

2022-02-08 05:16 UTC, AlexandrBehunkov approved these changes

2022-02-10 07:45 UTC, rartem approved these changes

2022-02-10 07:45 UTC, merged