update readme.md/russian_readme.md
savushkin-r-d/ptusa_main pull request #389
Opened 2022-03-29 08:48 UTC by blackbestiya

2022-03-30 12:25 UTC, idzm requested changes

2022-03-30 12:25 UTC, idzm commented on CMakePresets.json
> +            "displayName": "Visual Studio Community 2019 - x86 Debug",
```suggestion
            "displayName": "Visual Studio Community 2022 - x86 Debug",
```

2022-03-30 12:29 UTC, idzm requested changes

2022-03-30 12:29 UTC, idzm commented on readme.md
> +The CMake version required for the build: cmake_minimum_required(VERSION 3.13)
```suggestion
Detailed installation information can be obtained [here](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-160). The CMake version required for the build: `cmake_minimum_required(VERSION 3.13)`
```

2022-03-31 10:25 UTC, idzm requested changes

2022-03-31 10:25 UTC, idzm commented on CMakePresets.json
> +            }
Предлагается использовать три конфигурации: `windows-default`, `windows-default-VS2019`, `windows-default-VS2022`.

2022-03-31 10:25 UTC, idzm commented on russian_readme/readme.md
> +	Выбрать элемент запуска -> ptusa_main.exe
Доработать описание запуска с заданием следующих параметров командной строки:
`demo_projects/T1-PLCnext-Demo/main.plua path demo_projects/T1-PLCnext-Demo/ sys_path demo_projects/T1-PLCnext-Demo/sys/ debug`

2022-04-04 23:21 UTC, alexandraneroda commented
Попробую создать launch.vs.json для всего проекта, чтобы с помощью него в заданной конфигурации передавать параметры.

2022-04-05 13:46 UTC, idzm requested changes

2022-04-05 13:46 UTC, idzm commented on PAC/IoT/IOT_dev_lua.cpp
> +** Generated automatically by tolua++-1.0.92 on Fri Apr  1 15:48:19 2022.
Данный файл не должен изменяться в текущем запросе.

2022-04-05 13:46 UTC, idzm commented on PAC/common/PAC_dev_lua.cpp
> +** Generated automatically by tolua++-1.0.92 on Fri Apr  1 15:48:20 2022.
Данный файл не должен изменяться в текущем запросе.

2022-04-05 13:46 UTC, idzm commented on readme.md
> +Visual Studio Installer -> Development of classic applications in C++ -> C++ CMake tools for Windows
```suggestion
`Visual Studio Installer -> Development of classic applications in C++ -> C++ CMake tools for Windows`
```

2022-04-05 13:46 UTC, idzm commented on readme.md
> +Detailed installation information can be obtained [here](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-160). The CMake version required for the build: cmake_min
```suggestion
Detailed installation information can be obtained [here](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-160). The CMake version required for the build is 3.13 and above.
```

2022-04-05 13:46 UTC, idzm commented on russian_readme/readme.md
> +Visual Studio Installer -> Разработка классических приложений на C++ -> Средства CMake C++ для Windows
```suggestion
`Visual Studio Installer -> Разработка классических приложений на C++ -> Средства CMake C++ для Windows `
```

2022-04-05 13:46 UTC, idzm commented on russian_readme/readme.md
> +Подробную информацию по установке можно получить [здесь](https://docs.microsoft.com/ru-ru/cpp/build/cmake-projects-in-visual-studio?view=msvc-160). Версия CMake, необходимая для сборки: cmake_minimum
```suggestion
Подробную информацию по установке можно получить [здесь](https://docs.microsoft.com/ru-ru/cpp/build/cmake-projects-in-visual-studio?view=msvc-160). Версия CMake, необходимая для сборки: 3.13 и выше.
```

2022-04-06 13:59 UTC, idzm approved these changes

2022-04-07 06:55 UTC, idzm requested changes

2022-04-07 06:55 UTC, idzm commented on readme.md
> +	Project -> Delete cache and perform reconfiguration
```suggestion
If an error occurs after startup, then you should clear the CMake cache `Project -> Delete cache` and perform reconfiguration.
```

2022-04-07 06:55 UTC, idzm commented on russian_readme/readme.md
> +	Проект -> Удалить кэш и вполнить перенастройку
```suggestion
Если после запуска возникла ошибка, то следует очистить кэш CMake: `Проект -> Удалить кэш` и выполнить перенастройку.
```

2022-04-07 06:55 UTC, idzm commented on readme.md
> +	Select a launch item -> ptusa_main.exe
```suggestion
2. Launching a project in Microsoft Visual Studio Community 2022: `Select a launch item -> ptusa_main.exe`.
```

2022-04-07 06:55 UTC, idzm commented on russian_readme/readme.md
> +	Выбрать элемент запуска -> ptusa_main.exe //запуск тестового проекта (конфигурация запуска в VS)
```suggestion
2. Запуск проекта в Microsoft Visual Studio Community 2022: `Выбрать элемент запуска -> ptusa_main.exe`.
```

2022-04-07 13:49 UTC, rartem approved these changes

2022-04-08 05:49 UTC, merged