Add Ethernet scales
savushkin-r-d/ptusa_main pull request #480
Opened 2022-08-26 10:20 UTC by YarickBSTU

2022-09-05 06:34 UTC, idzm requested changes
Необходимо доработать - добавить создание соответствующих объектов при считывании описания устройств.

2022-09-05 06:35 UTC, idzm commented
Также необходимо дописать тесты.

2022-10-10 07:03 UTC, idzm requested changes

2022-10-10 07:03 UTC, idzm commented on test/PAC_dev_tests.cpp
> +    }
Надо доработать данный тест - проверять не только статус, но и значение веса.

2022-10-11 13:39 UTC, idzm submitted a review, later dismissed

2022-10-12 05:48 UTC, idzm approved these changes

2022-10-12 07:01 UTC, AlexandrBehunkov approved these changes

2022-10-12 07:02 UTC, merged