Updating Null to nullptr
savushkin-r-d/ptusa_main pull request #485
Opened 2022-09-05 09:05 UTC by alexandraneroda

2022-09-06 07:40 UTC, idzm requested changes

2022-09-06 07:40 UTC, idzm commented on PAC/common/rfid_reader_tolua.cpp
> -  if (!self) tolua_error(tolua_S,"invalid 'self' in accessing variable 'EPC_str'",NULL);
Данный файл генерируется автоматически, поэтому в него вносить изменения не нужно.

2022-09-08 06:24 UTC, alexandraneroda commented
В SonarCloud показывает, что нет покрытия тестами некоторых методов, в которые я не вносила изменения.

2022-09-23 09:58 UTC, idzm requested changes
Необходимо

2022-09-23 09:58 UTC, idzm commented on test/mcaRec_tests.cpp
> +    EXPECT_EQ( 1, 1, mngr.CopyRecipe( object ) );
Не корректный вариант тестирования. Можно просто вызвать метод объекта, а потом проверять его результаты выполнения:
```suggestion
    mngr.CopyRecipe();
    //Проверка результатов копирования рецептов.
```

2022-09-27 06:59 UTC, idzm approved these changes

2022-09-27 07:14 UTC, idzm commented
Методы `CopyRecipe`, `PasteRecipe`, `NullifyRecipe` в классах `TRecipeManager `и `TMediumRecipeManager` дублируются. @alexandraneroda - предлагаю внести изменения в данные классы и убрать избыточное дублирование кода.

2022-09-28 05:40 UTC, idzm commented
Данный запрос принимаем, задачу убрать избыточное дублирование кода вынесем отдельно.

2022-09-28 05:49 UTC, merged