addtion to readme
savushkin-r-d/ptusa_main pull request #543
Opened 2023-01-27 10:11 UTC by NogameNo-life

2023-01-27 11:10 UTC, Vasiliysamuilik commented on russian_readme/readme.md
> +На основе чистого файла заголовка tolua автоматеически генерирует код привязки для доступа к функциям C/C++ из Lua.
```suggestion
На основе чистого файла заголовка tolua автоматически генерирует код привязки для доступа к функциям C/C++ из Lua.
```

2023-01-30 06:01 UTC, idzm requested changes
Описание используемых модулей необходимо поместить в отдельный раздел. Для каждого компонента необходимо добавить ссылку на его сайт. Надо также ещё описать `googletest` - библиотека для модульного тестирования на языке C++.

2023-01-31 05:46 UTC, idzm requested changes

2023-01-31 05:46 UTC, idzm commented on readme.md
> +
Об особенностях установки данного модуля можно не писать.

2023-01-31 05:46 UTC, idzm commented on russian_readme/readme.md
> +Подробную информацию можно получить [здесь](https://web.tecgraf.puc-rio.br/~celes/tolua).
```suggestion
Подробную информацию можно получить [здесь](https://web.tecgraf.puc-rio.br/~celes/tolua/tolua-3.2.html).
```

2023-01-31 13:45 UTC, closed without merging