Add description of  libraries
savushkin-r-d/ptusa_main pull request #545
Opened 2023-02-02 07:27 UTC by NogameNo-life

2023-02-03 13:30 UTC, AlexandrBehunkov requested changes

2023-02-03 13:30 UTC, AlexandrBehunkov commented on russian_readme/readme.md
> +На основе чистого файла заголовка tolua автоматеически генерирует код привязки для доступа к функциям C/C++ из Lua.
```suggestion
На основе чистого файла заголовка tolua автоматически генерирует код привязки для доступа к функциям C/C++ из Lua.
```

2023-02-06 07:17 UTC, alexandraneroda requested changes

2023-02-06 07:17 UTC, alexandraneroda commented on readme.md
> +tolua is a tool that greatly simplifies the integration of C/C++ code with Lua. Based on a cleaned header file,
```suggestion
Tolua is a tool that greatly simplifies the integration of C/C++ code with Lua. Based on a cleaned header file, 
```

2023-02-06 07:17 UTC, alexandraneroda commented on readme.md
> +zlib is a software library used for data compression and is an abstraction of the DEFLATE compression algorithm used in their gzip file compression program.
```suggestion
Zlib is a software library used for data compression and is an abstraction of the DEFLATE compression algorithm used in their gzip file compression program.
```

2023-02-06 07:17 UTC, alexandraneroda commented on russian_readme/readme.md
> +tolua - это инструмент, который значительно упрощает интеграцию кода C/C++ с Lua.
```suggestion
Tolua - это инструмент, который значительно упрощает интеграцию кода C/C++ с Lua.
```

2023-02-06 07:17 UTC, alexandraneroda commented on russian_readme/readme.md
> +zlib — свободная кроссплатформенная библиотека для сжатия данных и является обобщением алгоритма сжатия данных DEFLATE,
```suggestion
Zlib — свободная кроссплатформенная библиотека для сжатия данных и является обобщением алгоритма сжатия данных DEFLATE, 
```

2023-02-06 07:24 UTC, alexandraneroda reviewed
Некоторые строки разделены после запятой в русской версии.

2023-02-06 10:02 UTC, idzm submitted a review, later dismissed

2023-02-06 12:12 UTC, AlexandrBehunkov approved these changes

2023-02-06 12:18 UTC, merged