Add simulation temperature sensor
savushkin-r-d/ptusa_main pull request #553
Opened 2023-02-16 14:17 UTC by NogameNo-life

2023-02-20 06:04 UTC, idzm requested changes

2023-02-20 06:04 UTC, idzm commented on PAC/common/imitation_TE.h
> +
Надо файл сохранить в кодировке utf-8.

2023-02-22 07:01 UTC, Vasiliysamuilik commented on PAC/common/imitation_TE.h
> +        float x = x_dis(gen);  // случайная величмина
```suggestion
        float x = x_dis(gen);  // случайная величина 
```

2023-03-02 11:39 UTC, idzm requested changes
Необходимо отформатировать код согласно стилю [Google C++](https://google.github.io/styleguide/cppguide.html).

2023-03-03 08:06 UTC, Vasiliysamuilik commented on PAC/common/imitation_TE.cpp
> +void imitation_TE::set_max(float max_in_range) { this->max = max_in_range; }
Для более чёткой прослеживаемости логического блока кода необходимо перенести на новую строку открывающие и закрывающие фигурные скобки.

Например:

```suggestion
void imitation_TE::set_max(float max_in_range) 
   { 
      this->max = max_in_range; 
   }
```

2023-03-03 08:06 UTC, Vasiliysamuilik commented on PAC/common/imitation_TE.cpp
> +}
```suggestion
bool imitation_TE::is_p() const 
        {
            // f(x)=1/(σ√2π)∙e^(-1/2∙((x-μ)/σ)^2) - функция Гаусса
            // σ - стандартное отклонение
            // x - случайная величина
            // μ - математическое ожидание

            return pow((st_deviation * sqrt(2 * M_PI)), -1) *
                       exp(-(pow(x - m_expec, 2) / (2 * pow(st_deviation, 2)))) >
                   0.01; 
        }// 0.01 вероятность того, что случайная величина находится на [25,30]
```

2023-03-03 08:06 UTC, Vasiliysamuilik commented on PAC/common/imitation_TE.h
> +};
Расположение комментариев.

```suggestion
private:
        float D = 0.234f;           // дисперсия
        float m_expec = 27.f;       // мат. ожидание
        float st_deviation = 0.48f; // стандартное отклонение
        float old_value = 25.7f;
        float x = get_random();     // случайная величина
        float max = 30.f;
        float min = 20.f;

        float get_random();
        bool is_p() const;          // функция расчета вероятности
        unsigned get_index() const;
};
```

2023-03-06 08:14 UTC, idzm requested changes

2023-03-06 08:14 UTC, idzm commented on PAC/common/imitation_TE.cpp
> +            // f(x)=1/(σ√2π)∙e^(-1/2∙((x-μ)/σ)^2) - функция Гаусса
Предлагается оформить формулы в новом формате - https://github.blog/2022-05-19-math-support-in-markdown/.

2023-04-28 11:41 UTC, idzm approved these changes

2023-04-28 12:22 UTC, Vasiliysamuilik approved these changes

2023-04-28 12:24 UTC, merged