[doc] Add user manual
savushkin-r-d/ptusa_main pull request #561
Opened 2023-03-09 14:12 UTC by NogameNo-life

Описывает изменения, вносимые  в #553.

2023-03-20 08:35 UTC, alexandraneroda requested changes

2023-03-20 08:35 UTC, alexandraneroda commented on docs/user_manual/ReadMe.md
> +В качастве аналогового устройства выступает датчик температуры. Значения температуры в данной программе соответствуют функции нормального распределения.
```suggestion
В качестве аналогового устройства выступает датчик температуры. Значения температуры в данной программе соответствуют функции нормального распределения.
```

2023-03-20 08:35 UTC, alexandraneroda commented on docs/user_manual/ReadMe.md
> +Например значения комнатной температуры могут находится примерно в интервале от 26 °C до 30°C. Если в течение всего дня фиксировать все изменения температуры в кабинете, то скорее всего мы увидим что
```suggestion
Например, значения комнатной температуры могут находиться, примерно, в интервале от 26 °C до 30°C. Если в течение всего дня фиксировать все изменения температуры в кабинете, то, скорее всего, мы увидим что-то на подобии [27.4, 26.9, 28.2, 29.1]. Математическим ожиданием или средним значением для такого интервала значений будет 27.9 °C.
```

2023-03-20 08:35 UTC, alexandraneroda commented on docs/user_manual/ReadMe.md
> +Математическое ожидание $-$ среднее значение случайной величины, в результате многократного повторения.
```suggestion
Математическое ожидание $-$ - среднее значение случайной величины в результате многократного повторения.
```

2023-03-20 08:35 UTC, alexandraneroda commented on docs/user_manual/ReadMe.md
> +Дисперсия $-$ расброс  значений случайной величины относительно мат. ожидания. Дисперсию можно вычислить по формуле ниже:
```suggestion
Дисперсия $-$ - разброс значений случайной величины относительно мат. ожидания. Дисперсию можно вычислить по формуле ниже:
```

2023-03-20 08:35 UTC, alexandraneroda commented on docs/user_manual/ReadMe.md
> +Квадрат в формуле нужен на случай отрицательных значений. Возвращаюсь к нашему примеру, дисперсия будет равна 0.695. Сама по себе дисперсия не очень информативна, более четкое понимание насколько рас
```suggestion
Квадрат в формуле нужен на случай отрицательных значений. Возвращаясь к нашему примеру, дисперсия будет равна 0.695. Сама по себе дисперсия не очень информативна, более четкое понимание насколько рассеяны значения дает стандартное отклонение:
```

2023-03-20 08:35 UTC, alexandraneroda commented on docs/user_manual/ReadMe.md
> +Дисперсия и мат. ожидание, плотность вероятности, задаются в параметрах конструктора, также в конструктор можно передать первоначальные значения $x$ и минимальную с максимальной температуры.
```suggestion
Дисперсия и мат. ожидание, плотность вероятности, задаются в параметрах конструктора. Также в конструктор можно передать первоначальные значения $x$ и минимальную с максимальной температуры.
```

2023-03-20 08:35 UTC, alexandraneroda commented on docs/user_manual/ReadMe.md
> +Главная функция ```get_value()```, которая и возвращает некую температуру, присваиваивает $x$ случайное значение из заданного диапазона температур, а затем считает чему равна функция, т. е  плотность
```suggestion
Главная функция ```get_value()```, которая и возвращает некую температуру, присваиваивает $x$ случайное значение из заданного диапазона температур, а затем считает чему равна функция, т. е  плотность вероятности в данной точке и больше ли она уже какого-то заданного ненулевого значения ```p```. Если условие истинно, то ```get_value()``` возвращает $x$ и записывает его в переменную ```prev_x```, которая хранит предыдущие значения температуры, на случай если у следующего $x$ будет слишком маленькая вероятность, тогда просто вернет старое значение температуры. ```prev_x``` инициализируется начальным значением функцией ```get_random()``` в теле конструктора, чтобы не вернуть ноль первым же значением $x$.
```

2023-03-20 08:35 UTC, alexandraneroda commented on docs/user_manual/ReadMe.md
> +Функция ```is_p()``` считает значение фукции плотности вероятности по [формуле](#markdown-header-нормальное-распределение) и возвращает  ```true``` если результат больше заданного значения плотности
```suggestion
Функция ```is_p()``` считает значение функции плотности вероятности по [формуле](#markdown-header-нормальное-распределение) и возвращает  ```true```, если результат больше заданного значения плотности вероятности ( переменной ```p``` ).
```

2023-03-20 08:35 UTC, alexandraneroda commented on docs/user_manual/ReadMe.md
> + ```get_value()``` присваивает $x$ число, которое возвращает ```get_random()```. В ```get_random()``` берется остаток от деления на размер вектора числа, возвращаемого функцией ```std::time```, дальш
```suggestion
 ```get_value()``` присваивает $x$ число, которое возвращает ```get_random()```. В ```get_random()``` берется остаток от деления на размер вектора числа, возвращаемого функцией ```std::time```, дальше это число используется в качестве индекса для извлечения из вектора случайного числа. Пусть даже вектор и типа ```float```, в нем все равно хранятся только целые числа, а нам нужны вещественные, поэтому к температуре суммируется случайное дробное число от 0 до 1. Данное число также берется из функции ```std::time```.
```

2023-03-21 08:52 UTC, alexandraneroda requested changes

2023-03-21 08:52 UTC, alexandraneroda commented on docs/user_manual/ReadMe.md
> +Дисперсия $-$ - разброс значений случайной величины относительно мат. ожидания. Дисперсию можно вычислить по формуле ниже:
```suggestion
Дисперсия $-$ разброс значений случайной величины относительно мат. ожидания. Дисперсию можно вычислить по формуле ниже:
```

2023-03-23 11:41 UTC, alexandraneroda submitted a review, later dismissed

2023-04-05 07:40 UTC, alexandraneroda requested changes

2023-04-05 07:40 UTC, alexandraneroda commented on docs/user_manual/ReadMe.md
> +Например, значения комнатной температуры могут находится примерно в интервале от 26 °C до 30°C. Если в течение всего дня фиксировать все изменения температуры в кабинете, то скорее всего мы увидим чт
```suggestion
Например, значения комнатной температуры могут находится примерно в интервале от 26 °C до 30°C. Если в течение всего дня фиксировать все изменения температуры в кабинете, то, скорее всего, мы увидим что-то на подобии [27.4, 26.9, 28.2, 29.1]. Математическим ожиданием или средним значением для такого интервала значений будет 27.9 °C.
```

2023-04-10 09:32 UTC, alexandraneroda requested changes

2023-04-10 09:32 UTC, alexandraneroda commented on docs/user_manual/ReadMe.md
> +Квадрат в формуле нужен на случай отрицательных значений. Возвращаюсь к нашему примеру, дисперсия будет равна 0.695. Сама по себе дисперсия не очень информативна, более четкое понимание насколько рас
```suggestion
Квадрат в формуле нужен на случай отрицательных значений. Возвращаясь к нашему примеру, дисперсия будет равна 0.695. Сама по себе дисперсия не очень информативна, более четкое понимание насколько рассеяны значения дает стандартное отклонение:
```

2023-04-10 09:56 UTC, alexandraneroda requested changes

2023-04-10 10:02 UTC, alexandraneroda requested changes

2023-04-10 10:02 UTC, alexandraneroda commented on docs/user_manual/ReadMe.md
> +Вероятность $p$ можно вычислить, посчитав площадь графика в конкретном интервале, площадь всего графика равна 1.
```suggestion
Вероятность $p$ можно вычислить, посчитав площадь графика в конкретном интервале. Площадь всего графика равна 1.
```

2023-04-10 10:02 UTC, alexandraneroda commented on docs/user_manual/ReadMe.md
> +Т. е. чем больше $\sigma$, тем «шире» график.
```suggestion
То есть чем больше $\sigma$, тем «шире» график.
```

2023-05-04 14:10 UTC, idzm approved these changes

2023-05-10 09:50 UTC, idzm commented
Вот исходные тексты программ, использованных для построения графиков:

1. m_expec.py
```python
from matplotlib import pyplot as plt
from norm_dist import NormDist

plt.style.use('dark_background') # задаем стииль окна
normobj = NormDist()
fig, ax = plt.subplots() # фигура для отрисовки графика
normobj.set_ax(ax)
ax.text(28, 0.1,r'$\mu $', fontsize=15, color='w') # ставим обозначение мат. ожидания 
ax.plot(normobj.x, normobj.y) # рисуем график 
plt.show()
```

2. norm_dist.py
```python
import numpy as np
from scipy.stats import norm

class NormDist:

    def __init__(self, x_min=26, x_max =30, mean=27.9, stdev=0.5, n=200):
        self.x_min = x_min # минимум диапозона распределния
        self.x_max = x_max # максимум диапозона распределния
        self.mean = mean # мат. ожидание
        self.stdev = stdev # стандартное отклонение 
        self.x = np.linspace(x_min, x_max, n)  # последовательность чисел в заданном интервале
        self.y= norm.pdf(self.x, loc=mean, scale=stdev) # функция для генерации чисел, соответствующих нормальному распредлению

    def set_ax(self, ax):
        ax.set_ylim(bottom=0) # задаем начало оси y от 0
        ax.grid(alpha=0.8,color='b') # добавляем сетку с прозрачностью 0.8 и задаем цвет
        ax.set_ylabel(r'$p$ (TE)') # называем ось y
        ax.set_xlabel('TE values') # называем ось x
        ax.vlines(self.mean, ymin=0, ymax=0.795, linewidths=2.0) # отрисовка линии по координатам x, y и верхней границе
```
3. stdev.py
```python
from matplotlib import pyplot as plt
import numpy as np
from scipy.stats import norm
from norm_dist import NormDist

plt.style.use('dark_background') # задаем стииль окна
fig, ax = plt.subplots() # фигура для отрисовки графика
normobj1 = NormDist() # создаем объект класса нормального распределения для инициализации параметров 
normobj1.set_ax(ax)  # настраиваем отображение осей 
mu_subtract_stdev = normobj1.mean - normobj1.stdev # начальная координата заливки
mu_plus_stdev = normobj1.mean + normobj1.stdev     # конечная координата заливки
px=np.arange(mu_subtract_stdev, mu_plus_stdev, 0.01)  # диапозон чисел для заливки с шагом 0.01
ax.fill_between(px, norm.pdf(px, loc=normobj1.mean, scale=normobj1.stdev), alpha=0.5, color='blue')   # функция для заливки
ax.text(27.5, 0.1, r'$\mu $ - $\sigma$', fontsize=15, color='w') # добавляем обозначения на график
ax.text(28, 0.1,r'$\mu $ + $\sigma$', fontsize=15, color='w') # добавляем текст на график
ax.plot(normobj1.x, normobj1.y) # рисуем график 
plt.show() # метод для показа графика, без него никак
```

4. subplots.py
```python
from matplotlib import pyplot as plt
import numpy as np
from scipy.stats import norm

plt.style.use('dark_background') # задаем стииль окна
fig, axs = plt.subplots(nrows= 2 , ncols= 2) # фигура для отрисовки графика

x_min, x_max = 26, 30 # задаем диапозон случайной величины 
mean = 27.9 # мат. ожидание 
stdev = 0.5   # стандартное отклонение

n = 200 # количестов элементов в linspace (массиве)
x = np.linspace(x_min, x_max, n)  # последовательность чисел в заданном интервале 

for ax in axs.flat:  #  в цикле выполняем одинаковые операции для каждого графика
    ax.set_ylim(bottom=0) # задаем начало оси y от 0
    ax.set_ylabel(r'$p$ (TE)') # называем ось y
    ax.set_xlabel('TE values') # называем ось x
    ax.plot(x, norm.pdf(x, loc=mean, scale=stdev))

axs[0,0].set_title(r'$p(X) < 27$')
axs[0,1].set_title(r'$p(X) > 28$')
axs[1,0].text(28.5, 0.6, r'$p(27 < X < 28)$', fontsize=10, color='w') # добавляем обозначения на график
axs[1,1].text(28.5, 0.6, r'$p(26 < X < 30)$', fontsize=10, color='w') # добавляем обозначения на график

px1=np.arange(26, 27, 0.01)
square1= norm.sf(x=27, loc=mean, scale=stdev) # вычисляем площадь графика, которая больше 27
axs[0,0].fill_between(px1, norm.pdf(px1, loc=mean, scale=stdev), alpha=0.5, color='m')  # заливка площади графика от 26 до 27
px_value1 = 1 - square1 # площадь графика от 26 до 27 
axs[0,0].text(27, 0.1, round(px_value1, 2), fontsize=15, color='c') # отмечаем на графике значение площади

px2=np.arange(28, 30, 0.01)
square2=norm.sf(x=28, loc=mean, scale=stdev) # вычисляем площадь графика, которая больше 28
axs[0,1].fill_between(px2, norm.pdf(px2, loc=mean, scale=stdev), alpha=0.5, color='m') # заливка площади графика от 28 до 30
axs[0,1].text(28, 0.3, round(square2, 2), fontsize=15, color= 'c')

px3=np.arange(27, 28, 0.01)
square3=norm(mean,stdev).cdf(28) - norm(mean, stdev).cdf(27) # вычисляем разность площади графика, в диапозоне [26,27]  от площади [28,30]
axs[1,0].fill_between(px3, norm.pdf(px3, loc=mean, scale=stdev), alpha=0.5, color='m')  # заливка площади графика от 27 до 28
axs[0,1].text(28, 0.3, round(square2, 2), fontsize=15, color= 'c')
axs[1,0].text(28, 0.3, round(square3, 2), fontsize=15, color='c')

px4=np.arange(26, 30, 0.01)
square4=norm(mean, stdev).sf(26) # вычисляем площадь графика в диапозоне [26,30]
axs[1,1].fill_between(px4, norm.pdf(px4, loc=mean, scale=stdev), alpha=0.5, color='m') # заливка площади графика от 26 до 30
axs[1,1].text(28, 0.3, round(square4, 2), fontsize=15, color='c')

plt.show()
```

2023-05-10 09:54 UTC, idzm approved these changes

2023-05-10 10:01 UTC, Vasiliysamuilik approved these changes

2023-05-10 13:55 UTC, merged