Dev OPCUA
savushkin-r-d/ptusa_main pull request #563
Opened 2023-03-14 14:01 UTC by YarickBSTU

2023-03-15 04:57 UTC, AlexandrBehunkov commented on PAC/common/OPCUA_bus_coupler_io.h
> +/// @brief ������ � �������� �����/������ c ������� OPCUA.
```suggestion
/// @brief ������ � �������� �����/������ c ������� OPCUA.
```

2023-03-15 04:58 UTC, AlexandrBehunkov requested changes

2023-03-15 04:58 UTC, AlexandrBehunkov commented on PAC/common/OPCUA_bus_coupler_io.h
> +/// @brief ������ � �������� �����/������ c ������� OPCUA.
@YarickBSTU необходимо исправить кодировку

2023-03-15 05:01 UTC, AlexandrBehunkov requested changes
```suggestion
/// @brief ������ � �������� �����/������ c ������� OPCUA.
```

2023-03-15 13:46 UTC, idzm requested changes

2023-03-15 13:46 UTC, idzm commented on demo_projects/T1-PLCnext-Demo
Демо-проект не должен изменяться, необходимо эти изменения убрать.

2023-03-15 13:46 UTC, idzm commented on PAC_control_projects/main_control_prg/main.cpp
> +    OPCUAServer::getInstance().Init(4841);
4841 - почему здесь такой порт?

2023-03-15 13:46 UTC, idzm commented on PAC_control_projects/main_control_prg/main.cpp
> +    //OPCUAServer::getInstance().CreateDevObjects();
Почему эта строка закомментирована?

2023-03-16 08:09 UTC, YarickBSTU commented on PAC_control_projects/main_control_prg/main.cpp
> +    OPCUAServer::getInstance().Init(4841);
В PLC есть свой встроенный OPC UA сервер. Запускается сам при включении сервисов PLCn с портом по умолчанию 4840. Возникают конфликты. Поэтому изменил порт

2023-03-16 08:16 UTC, YarickBSTU commented on PAC_control_projects/main_control_prg/main.cpp
> +    //OPCUAServer::getInstance().CreateDevObjects();
Уберу. Изначально планировалось создавать объекты на сервере на основе устройв из G_DEVICE_MANAGER. Возникли сложности с привязкой их к каналам ввода/вывода. Теперь объекты на сервере создаются на основе модулей ввода вывода, как бы имитируют каплер

2023-03-16 08:23 UTC, idzm commented on PAC_control_projects/main_control_prg/main.cpp
> +    //OPCUAServer::getInstance().CreateDevObjects();
Устройства и так связаны с каналами ввода/вывода. Это более высокий уровень абстракции. Если что-то не получилось, надо в отдельной ветви тогда это зафиксировать, чтобы можно было посмотреть в чем проблема.

2023-04-03 10:06 UTC, alexandraneroda commented on PAC/common/PAC_dev.h
> +        u_int get_device_count();
```suggestion
        u_int get_device_count() const;

```

2023-04-07 07:44 UTC, alexandraneroda requested changes

2023-04-07 07:44 UTC, alexandraneroda commented on PAC/common/OPCUAServer.cpp
> +    UA_ServerConfig_setMinimal(UA_Server_getConfig(server), portNumber, 0);
```suggestion
    UA_ServerConfig_setMinimal(UA_Server_getConfig(server), portNumber, nullptr);

```

2023-04-07 07:44 UTC, alexandraneroda commented on PAC/common/OPCUAServer.cpp
> +            oAttr, NULL, &deviceId );
```suggestion
            oAttr, nullptr, &deviceId );

```

2023-04-07 07:44 UTC, alexandraneroda commented on PAC/common/OPCUAServer.cpp
> +            valueAttr, G_DEVICE_MANAGER()->get_device(i), NULL);
```suggestion
            valueAttr, G_DEVICE_MANAGER()->get_device(i), nullptr);

```

2023-04-07 07:44 UTC, alexandraneroda commented on PAC/common/OPCUAServer.cpp
> +            stateAttr, G_DEVICE_MANAGER()->get_device(i), NULL);
```suggestion
            stateAttr, G_DEVICE_MANAGER()->get_device(i), nullptr);

```

2023-08-15 08:53 UTC, idzm approved these changes

2023-08-15 08:54 UTC, AlexandrBehunkov submitted a review, later dismissed

2023-08-16 09:57 UTC, merged