[doc] Edit block diagram
savushkin-r-d/ptusa_main pull request #582
Opened 2023-04-13 08:53 UTC by Vasiliysamuilik

Edit block diagram with diagramming and charting tool ["Mermaid"](https://mermaid.js.org/).

2023-05-10 09:58 UTC, idzm requested changes

2023-05-10 09:58 UTC, idzm commented on readme.md
> +1. The general schema of controller program work, made with [Mermaid](https://mermaid.js.org/):
```suggestion
1.  The general schema of controller program work, made with [Mermaid](https://mermaid.js.org/):
```

2023-05-11 06:22 UTC, idzm requested changes

2023-05-11 06:22 UTC, idzm commented on readme.md
> +1.  The general schema of controller program work, made with [Mermaid](https://mermaid.js.org/):
```suggestion
1.  The general schema of controller program work (in [Drakon](https://drakonhub.com) diagram language,  made with [Mermaid](https://mermaid.js.org/):
```

2023-05-11 06:22 UTC, idzm commented on readme.md
> +```
Оставляем здесь предыдущий вариант, так как есть существенные отличия:
```suggestion
<p align="center"><img src="docs/drakon_diagram/images/control_program_en.svg"></p>
```

2023-05-11 06:22 UTC, idzm commented on readme.md
> +    D[\Next unit/] --- E([End])
```suggestion
``` mermaid
flowchart TD
    A([2 Process execution]) --- B[/For each unit\]
    B --- C[[3 Execution of the unit <br/> procedure]]
    C --- D[\Next unit/]
    D --- E([End])
```

2023-05-11 06:22 UTC, idzm commented on readme.md
> +```
```suggestion
``` mermaid
flowchart TD
    A([3 Execution <br/> of the unit procedure]) --- B[/For each operation\]
    B --- C[[4 Execution <br/> of the operation]]
    C --- D[\Next operation/]
    D --- E([End])
```
```

2023-05-11 09:23 UTC, idzm requested changes

2023-05-11 09:23 UTC, idzm commented on readme.md
> +1.  The general schema of controller program work (in [Drakon](https://drakonhub.com) diagram language,  made with [Mermaid](https://mermaid.js.org/):
```suggestion
1.  The general schema of controller program work (in [Drakon](https://drakonhub.com) diagram language,  made with [Mermaid](https://mermaid.js.org/)):
```

2023-05-11 09:23 UTC, idzm commented on readme.md
> +    A([5 Execution <br/> of the steps]) --- A1[[6 Execution of the step]]
```suggestion
    A([5 Execution <br/> of the steps]) --- A1[[6 Execution of the <br/> main step]]
```

2023-05-12 05:25 UTC, idzm commented
Вот что получается для главной диаграммы:

``` mermaid
%%{init: { "flowchart": { "curve": "linear" } } }%%
flowchart TB
    A([1 Control program]) --- Z((_))
    Z((_)) --- B[/Initialization\]
    B[/Initialization\] --- C[\Control cycle/]
    C[\Control cycle/] -------- X((_))
    Z((_)) --- D[/Control cycle\]
    D[/Control cycle\]
    ---
    E>"Receiving input data
      from I/O modules,
      modbus devices"]
    E>"Receiving input data
       from I/O modules,
       modbus devices"]
    ---
    F[[2 Process execution]]
    F[[2 Process execution]]
    ---
    G{{"Writing output data
        to output modules,
        modbus devices"}}
    G{{"Writing output data
        to output modules,
        modbus devices"}}
    ---
    H["Interaction with
      the technological
      server SCADA-server"]
    H["Interaction with
       technological server
       (SCADA-server)"]
    ---
    I{{Need to terminate the program?}}
    I{{Need to terminate the program?}}
    ---
    |No| J[\Control cycle/]
    J[\Control cycle/] --- X((_))
    I{{"Need to terminate
        the program?"}}
    ---
    |Yes| K[\Completion/]
    K[\Completion/] --- X((_))
    X((_)) --- Z((_))
    Z((_)) --- L[/Completion\]
    L[/Completion\] --- M([End])
```

2023-05-12 05:28 UTC, idzm requested changes

2023-05-12 05:28 UTC, idzm commented on readme.md
> +    A([7 Execution <br/> of the step]) --- B(Action logic)
```suggestion
    A([7 Execution <br/> of the action]) --- B(Action logic)
```

2023-05-12 12:01 UTC, idzm approved these changes

2023-05-12 12:06 UTC, rartem approved these changes

2023-05-12 12:12 UTC, AlexandrBehunkov approved these changes

2023-05-12 13:26 UTC, merged