Program performance when working with Ethernet scales
savushkin-r-d/ptusa_main pull request #608
Opened 2023-08-16 09:12 UTC by YarickBSTU

Issue #596 
Добавлено асинхронное чтение по TCP
Программа больше не приостанавливается для чтения данных из весов

2023-08-24 11:52 UTC, NogameNo-life requested changes

2023-08-24 11:52 UTC, NogameNo-life commented on PAC/linux/l_tcp_client.cpp
> +    if (get_delta_millisec(asyncReciveTime) >= async_timeout && flag)\
```suggestion
    if (get_delta_millisec(asyncReciveTime) >= async_timeout && flag)
```

2023-08-24 11:52 UTC, NogameNo-life commented on PAC/linux/l_tcp_client.cpp
> +    }
```suggestion
    if ( res < 0 )
       {
       async_result = AR_SOCKETERROR;
       Disconnect();
       return 0;
       }
```

2023-08-24 11:52 UTC, NogameNo-life commented on PAC/linux/l_tcp_client.h
> +        bool flag;
По наименованию поля не очень понятно, для чего оно используется

2023-08-24 11:54 UTC, NogameNo-life requested changes

2023-08-24 11:54 UTC, NogameNo-life commented on PAC/linux/l_tcp_client.h
> +        bool flag;
По наименованию поля не очень понятно для чего оно используется

2023-08-25 11:50 UTC, NogameNo-life requested changes

2023-08-25 11:50 UTC, NogameNo-life commented on PAC/linux/l_tcp_client.cpp
> +        res = tcp_communicator_linux::recvtimeout(socket_number, (unsigned char*)buff,
Используй static_cast<> для приведения типов

2023-08-25 13:55 UTC, YarickBSTU commented on PAC/linux/l_tcp_client.cpp
> +        res = tcp_communicator_linux::recvtimeout(socket_number, (unsigned char*)buff,
static_cast не способен привести указатели разных типов

2023-08-28 08:15 UTC, idzm requested changes

2023-08-28 08:15 UTC, idzm commented on test/l_tcp_cmctr_tests.cpp
> +    EXPECT_EQ( true, res );
```suggestion
    EXPECT_TRUE( res );
```

2023-08-31 05:55 UTC, idzm requested changes
А что с реализацией для Windows?

2023-09-01 12:06 UTC, NogameNo-life commented on PAC/win/w_tcp_client.h
>  		win_tcp_client(const char* client_ip, unsigned int client_port, unsigned int client_id, unsigned char alarm_subclass, unsigned int exchange_buf_size = 256, unsigned long send_receive_timeout = 100)
```suggestion
		win_tcp_client( const char* client_ip, unsigned int client_port, unsigned int client_id, unsigned char alarm_subclass, unsigned int exchange_buf_size = 256, unsigned long send_receive_timeout = 100 );

```

2023-09-01 12:06 UTC, NogameNo-life commented on PAC/linux/l_tcp_client.h
>          virtual int AsyncSend(unsigned int bytestosend);
```suggestion
        virtual int AsyncSend( unsigned int bytestosend );
```

2023-09-01 12:09 UTC, NogameNo-life reviewed
Настрой себе автоформатирование кода https://github.com/savushkin-r-d/ptusa_main/blob/master/docs/style.md

2023-09-14 07:50 UTC, idzm requested changes
В чём трудности исправить замечания - https://sonarcloud.io/project/issues?id=savushkin-r-d_ptusa_main&pullRequest=608&resolved=false&types=CODE_SMELL?

2023-09-18 09:10 UTC, idzm submitted a review, later dismissed

2023-09-18 12:14 UTC, NogameNo-life requested changes

2023-09-18 12:36 UTC, YarickBSTU commented on PAC/linux/l_tcp_cmctr.cpp
> +        return true;
Если n = 1, то в таком случае вернется false. Раньше возвращалось true

2023-09-18 12:38 UTC, YarickBSTU commented on PAC/win/w_tcp_client.cpp
> +    return true;
Аналогичная ситуация

2023-09-18 12:56 UTC, NogameNo-life commented on PAC/linux/l_tcp_cmctr.cpp
> +        return true;
return n >= 1?

2023-09-19 05:01 UTC, YarickBSTU commented on PAC/linux/l_tcp_cmctr.cpp
> +        return true;
да

2023-09-20 07:50 UTC, idzm approved these changes

2023-09-20 07:56 UTC, NogameNo-life approved these changes

2023-09-27 06:49 UTC, idzm approved these changes

2023-09-27 06:50 UTC, merged