[doc] Fix toolchain docs
savushkin-r-d/ptusa_main pull request #610
Opened 2023-08-28 05:30 UTC by NogameNo-life

2023-08-31 08:27 UTC, idzm requested changes
Лучше оставить просто `2023.0 LTS`.

2023-09-04 07:30 UTC, idzm requested changes

2023-09-04 07:30 UTC, idzm commented on readme.md
> +Download the latest versions from the Phoenix Contact website https://www.phoenixcontact.com/products (for example from the **AXC F 2152** area) ```PLCnext Technology C++ toolchain for Windows```(cur
```suggestion
Download the latest versions from the Phoenix Contact [website](https://www.phoenixcontact.com/products) (for example, from the **AXC F 2152** area) ```PLCnext Technology C++ toolchain for Windows```(current is 2023.0 LTS) and ```sdk for Windows 64 bit``` (current is 2022.0.4 LTS), in the section Downloads->Software $-$ http://www.phoenixcontact.com/qr/2404267/softw.
```

2023-09-06 08:24 UTC, idzm requested changes

2023-09-06 08:24 UTC, idzm commented on readme.md
>  ## Using PLCnext Technology C++ Toolchain ##
```suggestion
## Using PLCnext Technology C++ Toolchain in Windows ##
```

2023-09-06 08:24 UTC, idzm commented on russian_readme/readme.md
>  ## Использование набора инструментов PLCnext Technology C++ ##
```suggestion
## Использование набора инструментов PLCnext Technology C++ для ОС Windows ##
```

2023-09-11 09:04 UTC, idzm approved these changes

2023-09-11 09:12 UTC, AlexandrBehunkov approved these changes

2023-09-18 12:14 UTC, rartem approved these changes

2023-09-18 12:35 UTC, merged