Dev devices statistics
savushkin-r-d/ptusa_main pull request #650
Opened 2024-02-20 13:01 UTC by YaroslavOzimok

Добавление сбора статистики устройств проекта. 

К собираемой статистике относятся следующие параметры:
 - Количества изменений состояния устройства, например, количество срабатывания цилиндра
 - Время активной работы (state > 0), например, время работы мотора
 - Ресурс устройства (задается в описании устройства в поле stat)
 - Износ устройства, отношение количества срабатываний к ресурсу устройства
 
 Предполагается передавать собранную статистику на сервер для отображения в Monitor в поле "Опции" конкретного устройства, как показано на рисунке
![image](https://github.com/savushkin-r-d/ptusa_main/assets/102078275/1d54923c-3cb6-4811-98df-d61229bff9cc)

2024-02-22 08:25 UTC, idzm requested changes

2024-02-22 08:25 UTC, idzm commented on PAC/common/statistic_manager.h
Надо сохранить данный файл в кодировке **UTF-8**.

2024-02-22 08:27 UTC, idzm requested changes

2024-02-22 08:27 UTC, idzm commented on PAC/common/toloa++/pkg/PAC_dev.hh
Надо сохранить данный файл в кодировке **UTF-8**.

2024-02-26 08:51 UTC, idzm requested changes
Все файлы должны быть в кодировке **UTF-8**.

2024-02-26 08:51 UTC, idzm commented on test/statistic_manager_tests.cpp
Надо сохранить данный файл в кодировке **UTF-8**.

2024-03-11 09:48 UTC, idzm reviewed
Необходимо доработать:
- [ ] устранить замечания https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&pullRequest=650&id=savushkin-r-d_ptusa_main;
- [ ] добавить тесты для [PAC_dev_lua.cpp](https://github.com/savushkin-r-d/ptusa_main/pull/650/files#diff-19e567a880525eabf1b188a066cc610acaa5920eb26e23486c6076656ece1785).

2024-03-19 06:38 UTC, idzm commented
@YaroslavOzimok - что по внесению необходимых изменений?

2024-03-27 08:38 UTC, idzm requested changes
Необходимо доработать:
- [x] устранить [замечания](https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&pullRequest=650&id=savushkin-r-d_ptusa_main) от Sonar
    - [ ] [Rewrite the code so that you no longer need this "delete".](https://sonarcloud.io/project/issues?pullRequest=650&open=AY3Gs5X3KzeT2nvyKRvD&id=savushkin-r-d_ptusa_main)
    - [ ] [Replace the use of "new" with an operation that automatically manages the memory.](https://sonarcloud.io/project/issues?pullRequest=650&open=AY3Gs5X3KzeT2nvyKRvE&id=savushkin-r-d_ptusa_main)
    - [ ] [Explicitly define or delete the missing copy constructor and copy assignment operator so that they will not be implicitly provided. Additionally, you may consider defining the move assignment operator and the move constructor.](https://sonarcloud.io/project/issues?pullRequest=650&open=AY3Pr3DE1y7vFCOD9ef0&id=savushkin-r-d_ptusa_main)
    - [ ] [Remove this class' destructor so that the class follows the rule of Zero.](https://sonarcloud.io/project/issues?pullRequest=650&open=AY3Pr3DE1y7vFCOD9ef1&id=savushkin-r-d_ptusa_main)
    - [x] ['statistic_manager' has virtual functions but non-virtual destructor.](https://sonarcloud.io/project/issues?pullRequest=650&open=AY3Pr3DE1y7vFCOD9efz&id=savushkin-r-d_ptusa_main)
- [ ] добавить тесты для **PAC_dev_lua.cpp** https://github.com/savushkin-r-d/ptusa_main/blob/0251cfae904020d13ca229d38fe7e4d622c24fc0/PAC/common/PAC_dev_lua.cpp#L14661-L14793.

2024-05-06 09:40 UTC, idzm requested changes
Предлагается данную функциональность реализовать на уровне класса [device](https://github.com/savushkin-r-d/ptusa_main/tree/master/docs/class_scheme) - чтобы все устройства сразу обладали данной функциональностью, плюс не отслеживать изменение состояния в отдельном классе каждый цикл работы программы (это требует дополнительных ресурсов).

2024-05-06 09:40 UTC, idzm commented on PAC/common/statistic_manager.cpp
> +	if( cmd == "SC" )
Сравнивать строки таким образом в данном контексте - слишком ресурсоёмкая операция. Что если сравнить первый символ на соответствие? Либо использовать `strcmp` (так как второй параметр указатель - `const char *prop`)?

2024-05-06 12:20 UTC, YaroslavOzimok commented on PAC/common/statistic_manager.cpp
> +	if( cmd == "SC" )
Если реализовывать сбор статистики на уровне класса Device, не приведет ли это к его перегруженности?

2025-01-23 11:38 UTC, idzm commented
Необходимо реализация данной функциональности на уровне класса `device` - чтобы соответствующие теги были сразу доступны без дополнительного описания на уровне скриптов `Lua`.

2025-01-23 11:38 UTC, closed without merging