Fix message buffer overflow error
savushkin-r-d/ptusa_main pull request #661
Opened 2024-03-04 13:48 UTC by idzm

2024-03-04 13:57 UTC, rartem submitted a review, later dismissed

2024-03-05 04:47 UTC, AlexandrBehunkov approved these changes

2024-03-05 10:44 UTC, YaroslavOzimok approved these changes

2024-03-06 06:12 UTC, idzm commented on PAC/common/operation_mngr.cpp
> +            *out.out = 0;
```suggestion
            *out.out = '\0';
```

2024-03-12 12:11 UTC, rartem submitted a review, later dismissed

2024-03-12 12:15 UTC, AlexandrBehunkov requested changes

2024-03-12 12:15 UTC, AlexandrBehunkov commented on PAC/common/operation_mngr.cpp
> +int operation::check_on_run_state(char* reason, int max_len ) const
```suggestion
int operation::check_on_run_state( char* reason, int max_len ) const

```

2024-03-12 12:23 UTC, AlexandrBehunkov requested changes

2024-03-12 12:23 UTC, AlexandrBehunkov commented on PAC/common/operation_mngr.cpp
> +    {
```suggestion
    {

```

2024-03-12 12:23 UTC, AlexandrBehunkov commented on test/operation_mngr_tests.cpp
> +		msg.c_str());
```suggestion
		msg.c_str() );
```

2024-03-12 12:38 UTC, AlexandrBehunkov approved these changes

2024-03-12 12:40 UTC, rartem approved these changes

2024-03-12 13:09 UTC, merged