[cip] Change circulation signal logic
savushkin-r-d/ptusa_main pull request #664
Opened 2024-03-13 13:13 UTC by rartem

Output of circulation signal on v2 supply is optional (off by default).
Closes #662

2024-03-13 13:14 UTC, AlexandrBehunkov submitted a review, later dismissed

2024-03-14 06:11 UTC, idzm requested changes

2024-03-14 06:11 UTC, idzm commented on PAC/common/cip_tech_def.cpp
> +                    && (!wasflip)
```suggestion
                    ) &&
                    (!wasflip)
```

2024-03-14 07:59 UTC, KUZMA-1989 approved these changes

2024-03-14 08:09 UTC, idzm approved these changes

2024-03-14 08:10 UTC, KUZMA-1989 approved these changes

2024-03-14 08:11 UTC, AlexandrBehunkov approved these changes

2024-03-14 09:20 UTC, merged