Added reverse seat connection logic swith for new AS-i mixproof valves
savushkin-r-d/ptusa_main pull request #667
Opened 2024-03-22 13:28 UTC by rartem

Closes #663

2024-03-22 13:29 UTC, AlexandrBehunkov approved these changes

2024-03-24 05:21 UTC, KUZMA-1989 requested changes
@rartem **Удали** артикул клапана **AL.9615-4000-11**, так как `он дискретный`. Только оставляем **AL.9615-4002-12**

2024-03-25 06:54 UTC, idzm requested changes

2024-03-25 06:54 UTC, idzm commented on PAC/common/PAC_dev.cpp
> +                    if (valve_AS_mix_proof::V70_ARTICLES.count(article) > 0)
```suggestion
                    if (valve_AS::V70_ARTICLES.count(article) > 0)
```

2024-03-25 06:54 UTC, idzm commented on test/PAC_dev_tests.cpp
> +    }
```suggestion
    }

```

2024-03-25 07:14 UTC, idzm approved these changes

2024-03-25 07:24 UTC, AlexandrBehunkov approved these changes

2024-03-25 07:29 UTC, SergeiSilakov approved these changes

2024-03-25 07:33 UTC, merged