Linux TCP client Async Recive Fix
savushkin-r-d/ptusa_main pull request #676
Opened 2024-04-05 05:29 UTC by YaroslavOzimok

При асинхронном чтении, если не нет данные для чтения, происходит отключение

2024-04-09 08:00 UTC, idzm commented
Подождём рецензию от @rartem.

2024-04-15 04:55 UTC, rartem submitted a review, later dismissed

2024-04-15 05:28 UTC, idzm requested changes

2024-04-15 05:28 UTC, idzm commented on test/l_tcp_cmctr_tests.cpp
> +    subhook_install( fail_recv );
Лишний вызов:
```suggestion
    subhook_install( fail_recv );
```

2024-04-15 09:59 UTC, rartem approved these changes

2024-04-16 07:25 UTC, idzm approved these changes

2024-04-22 13:01 UTC, merged