Fix emulator mode
savushkin-r-d/ptusa_main pull request #727
Opened 2024-08-14 12:35 UTC by idzm

Fixes #726.

2024-08-14 12:42 UTC, rartem submitted a review, later dismissed

2024-08-16 15:03 UTC, idzm commented on PAC/linux/l_tcp_cmctr.cpp
> -
Уже реализовано здесь:
https://github.com/savushkin-r-d/ptusa_main/blob/3d5953479921054f7344e827b847cb1d2ea90934/PAC/linux/l_tcp_cmctr.cpp#L104-L120

2024-08-20 06:47 UTC, rartem approved these changes

2024-08-20 07:36 UTC, AlexandrBehunkov requested changes

2024-08-20 07:36 UTC, AlexandrBehunkov commented on test/tcp_cmctr_tests.cpp
> +    linux_tcp_client cl( "127.0.0.1", G_CMMCTR->get_port(), 1, 1);
```suggestion
    linux_tcp_client cl( "127.0.0.1", G_CMMCTR->get_port(), 1, 1 );
```

2024-08-20 07:36 UTC, AlexandrBehunkov commented on test/tcp_cmctr_tests.cpp
> +    EXPECT_STREQ( cl.buff, "PAC accept");
```suggestion
    EXPECT_STREQ( cl.buff, "PAC accept" );
```

2024-08-20 08:11 UTC, AlexandrBehunkov approved these changes

2024-08-20 08:23 UTC, rartem approved these changes

2024-08-20 08:49 UTC, merged