[tests] Добавление тестов для менеджера рецептов
savushkin-r-d/ptusa_main pull request #779
Opened 2024-10-11 11:48 UTC by Lenonim

2024-10-15 09:50 UTC, idzm requested changes

2024-10-15 09:50 UTC, idzm commented on test/params_recipe_manager_tests.cpp
> +        "\t\t\t},\n\t\t},\n\t}\n", buff);
Здесь лучше использовать [строковые литералы](https://en.cppreference.com/w/cpp/language/string_literal). Вот пример:
https://github.com/savushkin-r-d/ptusa_main/blob/ec6839f9fd2e59f01adeecbb81d310120bd1e3c3/test/prj_mngr_tests.cpp#L109-L127

2024-10-17 12:22 UTC, Lenonim commented on test/params_recipe_manager_tests.cpp
> +        "\t\t\t},\n\t\t},\n\t}\n", buff);
Строковый литерал скорее всего не получиться использовать:

![image](https://github.com/user-attachments/assets/1d29ef37-c808-4bab-b249-5e29ab8be8aa)

2024-10-17 12:24 UTC, Lenonim commented on test/params_recipe_manager_tests.cpp
> +        "\t\t\t},\n\t\t},\n\t}\n", buff);
Можно либо каким-то образом привести buff к строке с литералом, либо сделать так, чтобы функция save_device возвращала приведённые к строковому литералу результат.

2024-10-23 07:16 UTC, idzm requested changes

2024-10-23 07:16 UTC, idzm commented on test/g_device_tests.cpp
> +        }
Что данный тест проверяет?

2024-10-23 07:16 UTC, idzm commented on test/params_recipe_manager_tests.cpp
> +
Предлагаю переписать данный фрагмент на основе следующего (сделать возможным через параметр передачу времени, которое должно пройти):
https://github.com/savushkin-r-d/ptusa_main/blob/0f8b5c2a4336d38f703778f627ee097d72e288b1/test/includes.h#L9-L16

2024-10-23 15:22 UTC, Lenonim commented on test/params_recipe_manager_tests.cpp
> +
Отличная мысль

2024-10-23 15:27 UTC, Lenonim commented on test/g_device_tests.cpp
> +        }
Этот тест ещё дорабатывается. В планах сделать проверку того, что функция print() выводит на экран. Т.к. у неё тип возвращаемого значения void, то проверить традиционно не получится.

2024-10-28 09:02 UTC, idzm approved these changes

2024-10-28 09:03 UTC, merged